name: dartx_validate
description: Dartx Validate is a Zod-like validation library for Dart, providing a simple and expressive way to validate data structures.
version: 1.1.0
repository: https://github.com/dartx-web/dartx_validate
homepage: https://github.com/dartx-web/dartx_validate

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
